apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weeknd
  description: A cool go app
  annotations:
    backstage.io/kubernetes-id: weeknd
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: cooktheryan/weeknd
spec:
  type: app
  lifecycle: production
  owner: rhdh