---
apiVersion: v1
kind: Secret
metadata:
  name: my-go-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: 'https://github.com/cooktheryan/weeknd.git'